services:
  backend:
    build:
      context: ./backend   # This tells Docker Compose to use the Dockerfile in the backend folder
    ports:
      - "8080:8080"        # Exposes backend on localhost:8080
    networks:
      - app-network        # Creates a shared network between services
    depends_on:
      - postgres_database  # Ensure the backend depends on the databases
      - mongodb_database
      - rabbitmq
    environment:
      - POSTGRES_DATABASE_URL=jdbc:postgresql://postgres_database:5432/PollApp
      - MONGO_DATABASE_URL=mongodb://mongodb_database:27017/events
      - RABBITMQ_HOSTNAME=rabbitmq

  frontend:
    build:
      context: ./frontend  # This tells Docker Compose to use the Dockerfile in the frontend folder
    ports:
      - "5173:5173"        # Exposes frontend on localhost:3000
    networks:
      - app-network        # Shared network for frontend and backend
    depends_on:
      - backend            # Ensures backend starts before frontend
    environment:
      - VITE_BACKEND_URL=http://backend:8080

  postgres_database:
    extends:
      service: postgres_database
      file: ./backend/database/docker-compose-db.yml


  mongodb_database:
    extends:
      service: mongodb_database
      file: ./backend/database/docker-compose-db.yml


  rabbitmq:
    extends:
      service: rabbitmq
      file: ./backend/database/docker-compose-db.yml


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:



