name: Sploinkyboink CI
run-name: ${{ github.actor }} pushed, testing.

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]  # Define both frontend and backend tasks

    steps:
      # Common Step: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Backend-Specific Steps
      - name: Set up JDK for backend
        if: matrix.service == 'backend'  # Only run for the backend
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle packages
        if: matrix.service == 'backend'
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        if: matrix.service == 'backend'
        run: chmod +x ./gradlew

      - name: Build backend with Gradle
        if: matrix.service == 'backend'
        run: ./gradlew clean build

      - name: Run backend tests
        if: matrix.service == 'backend'
        run: ./gradlew test


      # Frontend-Specific Steps
      - name: Set up Node.js for frontend
        if: matrix.service == 'frontend'  # Only run for the frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        if: matrix.service == 'frontend'
        run: npm install --prefix ./frontend

      - name: Build frontend
        if: matrix.service == 'frontend'
        run: npm run build --prefix ./frontend

      # Common Step: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Backend Docker Build and Push
      - name: Build and push backend Docker image
        if: matrix.service == 'backend'
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/krissibro/dat250-sploinkyboink-backend:latest
            ghcr.io/krissibro/dat250-sploinkyboink-backend:${{ github.sha }}

      # Frontend Docker Build and Push
      - name: Build and push frontend Docker image
        if: matrix.service == 'frontend'
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/krissibro/dat250-sploinkyboink-frontend:latest
            ghcr.io/krissibro/dat250-sploinkyboink-frontend:${{ github.sha }}

